version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: '⬆️ deps:'
      prefix-development: '⬆️ deps(dev):'
    rebase-strategy: auto
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: '⬆️ deps(gha):'