name: Add an extension
description: I want an extension to be published via this repo
title: "[extension.id]: Publish to OpenVSX"
labels: ["extension"]
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission checklist
      description: We require new publication requests to be first communicated with the extension's maintainers, only if they don't want to / can't publish it on their own or are unresponsive we will accept the request
      options:
        - label: I have reached out to the extension maintainers to publish to OpenVSX directly
          required: true
        - label: This extension has an [OSI-approved OSS license](https://opensource.org/licenses)
          required: true
  - type: textarea
    id: notes
    attributes:
      label: Anything else?
      description: If there are further details that could help with publishing the extension, put them here
