name: Publish VS Code extensions to open-vsx.org

on:
  schedule:
    # Run at 03:03 UTC every day.
    - cron:  '3 3 * * *'

jobs:
  download_and_publish:
    name: Download extensions and publish updates to open-vsx.org
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: node publish-extensions
