name: Validate PR

on:
  pull_request:
    branches: [master]

jobs:
  publish_extensions:
    env:
      VALIDATE_PR: true
      SKIP_PUBLISH: true
      FORCE: true
    name: Validate PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Validate JSON files
        run: |
          echo "Validating JSON files..."

          # Validate extensions.json
          echo "Validating extensions.json..."
          if ! jq empty extensions.json >/dev/null 2>&1; then
            echo "❌ extensions.json is not valid JSON"
            exit 1
          fi
          echo "✓ extensions.json is valid JSON"

          # Validate extension-control/extensions.json
          echo "Validating extension-control/extensions.json..."
          if ! jq empty extension-control/extensions.json >/dev/null 2>&1; then
            echo "❌ extension-control/extensions.json is not valid JSON"
            exit 1
          fi
          echo "✓ extension-control/extensions.json is valid JSON"

          # Validate extensions-schema.json
          echo "Validating extensions-schema.json..."
          if ! jq empty extensions-schema.json >/dev/null 2>&1; then
            echo "❌ extensions-schema.json is not valid JSON"
            exit 1
          fi
          echo "✓ extensions-schema.json is valid JSON"

          # Validate extension-control/schema.json
          echo "Validating extension-control/schema.json..."
          if ! jq empty extension-control/schema.json >/dev/null 2>&1; then
            echo "❌ extension-control/schema.json is not valid JSON"
            exit 1
          fi
          echo "✓ extension-control/schema.json is valid JSON"

          echo "✅ All JSON files are valid!"
      - uses: actions/setup-node@v4.3.0
        with:
          node-version: "22.x"
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: npm install
      - run: npm i -g @vscode/vsce pnpm
      - name: Set up pyenv
        uses: "gabrielfalcao/pyenv-action@32ef4d2c861170ce17ded56d10329d83f4c8f797"
        with:
            command: python --version
      - name: Set default global version
        run: |
          pyenv install 3.8
          pyenv global 3.8
      - run: echo "EXTENSIONS=$(node diff-extensions)" >> $GITHUB_ENV
      - uses: actions/github-script@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          EXTENSIONS: ${{ env.EXTENSIONS }}
        with:
          script: |
            const script = require('./scripts/publish-extensions.js');
            await script(async (extension, context) => {
              console.log(`Would publish ${extension.id} with context:`, JSON.stringify(context, null, 2));
            });
      - name: Report results
        run: bun run ./report-extensions.ts
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: report
          path: |
            /tmp/stat.json
            /tmp/result.md
      - name: Upload job summary
        run: cat /tmp/result.md >> $GITHUB_STEP_SUMMARY
      - name: Save PR number to file
        if: github.event_name == 'pull_request'
        run: echo ${{ github.event.number }} > PR_NUMBER.txt
      - name: Archive PR number
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: PR_NUMBER
          path: PR_NUMBER.txt


