name: Validate PR

on:
  pull_request:
    branches: [master]

jobs:
  publish_extensions:
    env:
      VALIDATE_PR: true
      SKIP_PUBLISH: true
      FORCE: true
    name: Validate PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3.8.1
        with:
          node-version: "18.x"
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: npm install
      - run: npm i -g @vscode/vsce
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - run: EXTENSIONS=$(node diff-extensions) node publish-extensions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Report results
        run: bun run ./report-extensions.ts
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: report
          path: |
            /tmp/stat.json
            /tmp/result.md
      - name: Upload job summary
        run: cat /tmp/result.md >> $GITHUB_STEP_SUMMARY
