name: Validate PR

on:
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  publish_extensions:
    env:
      VALIDATE_PR: true
      SKIP_PUBLISH: true
      FORCE: true
    name: Validate PR
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: "24.x"
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
        with:
          bun-version: latest
      - run: npm install
      - run: npm i -g @vscode/vsce pnpm
      - name: Set up pyenv
        uses: gabrielfalcao/pyenv-action@a1fc55906be92612782934c70e3985b940bd0165 # v18
        with:
            command: python --version
      - name: Set default global version
        run: |
          pyenv install 3.8
          pyenv global 3.8
      - run: echo "EXTENSIONS=$(node diff-extensions)" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          EXTENSIONS: ${{ env.EXTENSIONS }}
        with:
          script: |
            const script = require('./scripts/publish-extensions.js');
            await script(async (extension, context) => {
              console.log(`Would publish ${extension.id} with context:`, JSON.stringify(context, null, 2));
            });
      - name: Report results
        run: bun run ./report-extensions.ts
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: always()
        with:
          name: report
          path: |
            /tmp/stat.json
            /tmp/result.md
      - name: Upload job summary
        run: cat /tmp/result.md >> $GITHUB_STEP_SUMMARY
